/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SchoolService } from "../school.service";
import { SchoolCreateInput } from "./SchoolCreateInput";
import { School } from "./School";
import { SchoolFindManyArgs } from "./SchoolFindManyArgs";
import { SchoolWhereUniqueInput } from "./SchoolWhereUniqueInput";
import { SchoolUpdateInput } from "./SchoolUpdateInput";
import { AccessKeyFindManyArgs } from "../../accessKey/base/AccessKeyFindManyArgs";
import { AccessKey } from "../../accessKey/base/AccessKey";
import { AccessKeyWhereUniqueInput } from "../../accessKey/base/AccessKeyWhereUniqueInput";

export class SchoolControllerBase {
  constructor(protected readonly service: SchoolService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: School })
  async createSchool(@common.Body() data: SchoolCreateInput): Promise<School> {
    return await this.service.createSchool({
      data: data,
      select: {
        address: true,
        contactEmail: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [School] })
  @ApiNestedQuery(SchoolFindManyArgs)
  async schools(@common.Req() request: Request): Promise<School[]> {
    const args = plainToClass(SchoolFindManyArgs, request.query);
    return this.service.schools({
      ...args,
      select: {
        address: true,
        contactEmail: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: School })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async school(
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<School | null> {
    const result = await this.service.school({
      where: params,
      select: {
        address: true,
        contactEmail: true,
        createdAt: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: School })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSchool(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() data: SchoolUpdateInput
  ): Promise<School | null> {
    try {
      return await this.service.updateSchool({
        where: params,
        data: data,
        select: {
          address: true,
          contactEmail: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: School })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSchool(
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<School | null> {
    try {
      return await this.service.deleteSchool({
        where: params,
        select: {
          address: true,
          contactEmail: true,
          createdAt: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/accessKeys")
  @ApiNestedQuery(AccessKeyFindManyArgs)
  async findAccessKeys(
    @common.Req() request: Request,
    @common.Param() params: SchoolWhereUniqueInput
  ): Promise<AccessKey[]> {
    const query = plainToClass(AccessKeyFindManyArgs, request.query);
    const results = await this.service.findAccessKeys(params.id, {
      ...query,
      select: {
        createdAt: true,
        expiryDate: true,
        id: true,
        procurementDate: true,

        school: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/accessKeys")
  async connectAccessKeys(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: AccessKeyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accessKeys: {
        connect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/accessKeys")
  async updateAccessKeys(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: AccessKeyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accessKeys: {
        set: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/accessKeys")
  async disconnectAccessKeys(
    @common.Param() params: SchoolWhereUniqueInput,
    @common.Body() body: AccessKeyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accessKeys: {
        disconnect: body,
      },
    };
    await this.service.updateSchool({
      where: params,
      data,
      select: { id: true },
    });
  }
}
