/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AccessLog } from "./AccessLog";
import { AccessLogCountArgs } from "./AccessLogCountArgs";
import { AccessLogFindManyArgs } from "./AccessLogFindManyArgs";
import { AccessLogFindUniqueArgs } from "./AccessLogFindUniqueArgs";
import { CreateAccessLogArgs } from "./CreateAccessLogArgs";
import { UpdateAccessLogArgs } from "./UpdateAccessLogArgs";
import { DeleteAccessLogArgs } from "./DeleteAccessLogArgs";
import { AccessKey } from "../../accessKey/base/AccessKey";
import { User } from "../../user/base/User";
import { AccessLogService } from "../accessLog.service";
@graphql.Resolver(() => AccessLog)
export class AccessLogResolverBase {
  constructor(protected readonly service: AccessLogService) {}

  async _accessLogsMeta(
    @graphql.Args() args: AccessLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [AccessLog])
  async accessLogs(
    @graphql.Args() args: AccessLogFindManyArgs
  ): Promise<AccessLog[]> {
    return this.service.accessLogs(args);
  }

  @graphql.Query(() => AccessLog, { nullable: true })
  async accessLog(
    @graphql.Args() args: AccessLogFindUniqueArgs
  ): Promise<AccessLog | null> {
    const result = await this.service.accessLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AccessLog)
  async createAccessLog(
    @graphql.Args() args: CreateAccessLogArgs
  ): Promise<AccessLog> {
    return await this.service.createAccessLog({
      ...args,
      data: {
        ...args.data,

        accessKey: args.data.accessKey
          ? {
              connect: args.data.accessKey,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => AccessLog)
  async updateAccessLog(
    @graphql.Args() args: UpdateAccessLogArgs
  ): Promise<AccessLog | null> {
    try {
      return await this.service.updateAccessLog({
        ...args,
        data: {
          ...args.data,

          accessKey: args.data.accessKey
            ? {
                connect: args.data.accessKey,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AccessLog)
  async deleteAccessLog(
    @graphql.Args() args: DeleteAccessLogArgs
  ): Promise<AccessLog | null> {
    try {
      return await this.service.deleteAccessLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => AccessKey, {
    nullable: true,
    name: "accessKey",
  })
  async getAccessKey(
    @graphql.Parent() parent: AccessLog
  ): Promise<AccessKey | null> {
    const result = await this.service.getAccessKey(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: AccessLog): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
